<?xml version="1.0" encoding="utf-8"?><Database Name="MyNewDB" Class="DBLibContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KhagendraPC;Initial Catalog=MyNewDB;Integrated Security=True" SettingsObjectName="LibMgmt.Properties.Settings" SettingsPropertyName="MyNewDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Author" Member="Authors">
    <Type Name="Author">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.checklogginuser" Method="checklogginuser">
    <Parameter Name="username" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="checklogginuserResult">
      <Column Name="role" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>